name: Woerterbuch
options:
  bundleIdPrefix: com.example
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "10.0"
targets:
  Woerterbuch:
    type: application
    platform: iOS
    sources:
      - path: Woerterbuch
        excludes:
          - "Assets/*.sketch"
    settings:
      base:
        SWIFT_VERSION: 5.0